[package]
name = "benchmarks"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
milli = { path = "../milli" }

[target.'cfg(target_os = "linux")'.dependencies]
jemallocator = "0.3.2"

[dev-dependencies]
heed = { git = "https://github.com/irevoire/heed", branch = "main", default-features = false, features = ["lmdb", "sync-read-txn"] }
criterion = { version = "0.3.4", features = ["html_reports"] }

[build-dependencies]
anyhow = "1.0"
bytes = "1.0"
flate2 = "1.0.20"
convert_case = "0.4"
reqwest = { version = "0.11.3", features = ["blocking", "rustls-tls"], default-features = false }

[[bench]]
name = "songs"
harness = false

[[bench]]
name = "wiki"
harness = false
